title: Andy's Portfolio
author:
   name: Andy Cheng
   email: andy_cheng@berkeley.edu
description: ""

remote_theme: jekyll/minima@d4d779a
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima_skin: dark

minima:
  nav_pages:
    - games.md
    - apps.md
    - models.md
  social_links:
    rss: none

show_excerpts: false

minima:
  skin: dark

hide_site_feed_link: true

feed:
  path: false