title: Andy's Portfolio
author:
   name: Andy Cheng
   email: andycheng2018@gmail.com
description: ""

remote_theme: jekyll/minima@d4d779a
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima_skin: dark

nav_pages:
  - games.md
  - apps.md
  - models.md

minima:
  skin: dark

hide_site_feed_link: true